CREATE USER 'sqlayer_test'@'%' IDENTIFIED WITH mysql_native_password AS '***';
GRANT USAGE ON *.* TO 'sqlayer_test'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `sqlayer_test`;
GRANT ALL PRIVILEGES ON `sqlayer\_test`.* TO 'sqlayer_test'@'%';
